name: MTDrugs
version: '2.4'
main: dev.thebathduck.drugs.Drugs
authors: [ SubwayKoekje, Milan_V, OmeWillem ]
description: 'Minetopia Drugs opnieuw uitgevonden.'
depend: [WorldGuard]
commands:
  mtdrugs:
    description: Hoofd command, gebruik /mtdrugs help om meer informatie te krijgen.
